// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "VsoftmaxTB__Syms.h"


void VsoftmaxTB___024root__trace_chg_0_sub_0(VsoftmaxTB___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void VsoftmaxTB___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    VsoftmaxTB___024root__trace_chg_0\n"); );
    // Init
    VsoftmaxTB___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<VsoftmaxTB___024root*>(voidSelf);
    VsoftmaxTB__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    VsoftmaxTB___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void VsoftmaxTB___024root__trace_chg_0_sub_0(VsoftmaxTB___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    VsoftmaxTB__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VsoftmaxTB___024root__trace_chg_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    VlWide<10>/*319:0*/ __Vtemp_8;
    // Body
    if (VL_UNLIKELY((vlSelf->__Vm_traceActivity[1U] 
                     | vlSelf->__Vm_traceActivity[2U]))) {
        bufp->chgWData(oldp+0,(vlSelf->softmaxTB__DOT__inputs),320);
        bufp->chgBit(oldp+10,(vlSelf->softmaxTB__DOT__enable));
        bufp->chgIData(oldp+11,(vlSelf->softmaxTB__DOT__count),32);
        bufp->chgIData(oldp+12,(vlSelf->softmaxTB__DOT__inputs[0U]),32);
        bufp->chgIData(oldp+13,(vlSelf->softmaxTB__DOT__inputs[1U]),32);
        bufp->chgIData(oldp+14,(vlSelf->softmaxTB__DOT__inputs[2U]),32);
        bufp->chgIData(oldp+15,(vlSelf->softmaxTB__DOT__inputs[3U]),32);
        bufp->chgIData(oldp+16,(vlSelf->softmaxTB__DOT__inputs[4U]),32);
        bufp->chgIData(oldp+17,(vlSelf->softmaxTB__DOT__inputs[5U]),32);
        bufp->chgIData(oldp+18,(vlSelf->softmaxTB__DOT__inputs[6U]),32);
        bufp->chgIData(oldp+19,(vlSelf->softmaxTB__DOT__inputs[7U]),32);
        bufp->chgIData(oldp+20,(vlSelf->softmaxTB__DOT__inputs[8U]),32);
        bufp->chgIData(oldp+21,(vlSelf->softmaxTB__DOT__inputs[9U]),32);
    }
    if (VL_UNLIKELY((vlSelf->__Vm_traceActivity[1U] 
                     | vlSelf->__Vm_traceActivity[4U]))) {
        bufp->chgIData(oldp+22,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[0]),32);
        bufp->chgIData(oldp+23,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[1]),32);
        bufp->chgIData(oldp+24,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[2]),32);
        bufp->chgIData(oldp+25,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[3]),32);
        bufp->chgIData(oldp+26,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[4]),32);
        bufp->chgIData(oldp+27,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[5]),32);
        bufp->chgIData(oldp+28,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[6]),32);
        bufp->chgIData(oldp+29,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[7]),32);
        bufp->chgIData(oldp+30,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[8]),32);
        bufp->chgIData(oldp+31,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[9]),32);
        bufp->chgIData(oldp+32,(vlSelf->softmaxTB__DOT__soft1__DOT__expSums[10]),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[3U])) {
        bufp->chgWData(oldp+33,(vlSelf->softmaxTB__DOT__outputs),320);
        bufp->chgBit(oldp+43,(vlSelf->softmaxTB__DOT__ackSoft));
        bufp->chgCData(oldp+44,(vlSelf->softmaxTB__DOT__soft1__DOT__mulCounter),4);
        bufp->chgIData(oldp+45,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__P2D),32);
        bufp->chgIData(oldp+46,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__D1),32);
        bufp->chgIData(oldp+47,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__D2),32);
        bufp->chgIData(oldp+48,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__D3),32);
        bufp->chgIData(oldp+49,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__D4),32);
        bufp->chgBit(oldp+50,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul1__DOT__sign));
        bufp->chgCData(oldp+51,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul1__DOT__exponent),8);
        bufp->chgIData(oldp+52,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+53,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul1__DOT__fraction),48);
        bufp->chgIData(oldp+55,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+56,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+57,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul1__DOT__eout));
        bufp->chgIData(oldp+58,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul1__DOT__unnamedblk1__DOT__i),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[4U])) {
        bufp->chgIData(oldp+59,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellout__genblk2__BRA__9__KET____DOT__FADD1____pinNumber3),32);
        __Vtemp_8[0U] = vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.Y;
        __Vtemp_8[1U] = vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.Y;
        __Vtemp_8[2U] = vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.Y;
        __Vtemp_8[3U] = vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.Y;
        __Vtemp_8[4U] = vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.Y;
        __Vtemp_8[5U] = vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.Y;
        __Vtemp_8[6U] = vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.Y;
        __Vtemp_8[7U] = vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.Y;
        __Vtemp_8[8U] = (IData)((((QData)((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.Y)) 
                                  << 0x20U) | (QData)((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.Y))));
        __Vtemp_8[9U] = (IData)(((((QData)((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.Y)) 
                                   << 0x20U) | (QData)((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.Y))) 
                                 >> 0x20U));
        bufp->chgWData(oldp+60,(__Vtemp_8),320);
        bufp->chgSData(oldp+70,((((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.ack) 
                                  << 9U) | (((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.ack) 
                                             << 8U) 
                                            | (((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.ack) 
                                                << 7U) 
                                               | (((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.ack) 
                                                   << 6U) 
                                                  | (((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.ack) 
                                                      << 5U) 
                                                     | (((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.ack) 
                                                         << 4U) 
                                                        | (((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.ack) 
                                                            << 3U) 
                                                           | (((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.ack) 
                                                               << 2U) 
                                                              | (((IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.ack) 
                                                                  << 1U) 
                                                                 | (IData)(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.ack))))))))))),10);
        bufp->chgIData(oldp+71,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.Y),32);
        bufp->chgIData(oldp+72,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellout__genblk2__BRA__0__KET____DOT__FADD1____pinNumber3),32);
        bufp->chgCData(oldp+73,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__0__KET____DOT__FADD1__DOT__exponent),8);
        bufp->chgCData(oldp+74,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__0__KET____DOT__FADD1__DOT__exponentA),8);
        bufp->chgIData(oldp+75,((0x800000U | (0x7fffffU 
                                              & vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.Y))),24);
        bufp->chgIData(oldp+76,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.Y),32);
        bufp->chgIData(oldp+77,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellout__genblk2__BRA__1__KET____DOT__FADD1____pinNumber3),32);
        bufp->chgBit(oldp+78,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__sign));
        bufp->chgCData(oldp+79,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__exponent),8);
        bufp->chgIData(oldp+80,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__mantissa),23);
        bufp->chgIData(oldp+81,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__fraction),24);
        bufp->chgCData(oldp+82,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__exponentA),8);
        bufp->chgCData(oldp+83,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__exponentB),8);
        bufp->chgIData(oldp+84,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__fractionA),24);
        bufp->chgIData(oldp+85,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__fractionB),24);
        bufp->chgSData(oldp+86,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+87,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__cout));
        bufp->chgBit(oldp+88,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__eout));
        bufp->chgIData(oldp+89,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__1__KET____DOT__FADD1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+90,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.Y),32);
        bufp->chgIData(oldp+91,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellout__genblk2__BRA__2__KET____DOT__FADD1____pinNumber3),32);
        bufp->chgBit(oldp+92,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__sign));
        bufp->chgCData(oldp+93,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__exponent),8);
        bufp->chgIData(oldp+94,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__mantissa),23);
        bufp->chgIData(oldp+95,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__fraction),24);
        bufp->chgCData(oldp+96,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__exponentA),8);
        bufp->chgCData(oldp+97,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__exponentB),8);
        bufp->chgIData(oldp+98,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__fractionA),24);
        bufp->chgIData(oldp+99,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__fractionB),24);
        bufp->chgSData(oldp+100,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+101,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__cout));
        bufp->chgBit(oldp+102,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__eout));
        bufp->chgIData(oldp+103,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__2__KET____DOT__FADD1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+104,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.Y),32);
        bufp->chgIData(oldp+105,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellout__genblk2__BRA__3__KET____DOT__FADD1____pinNumber3),32);
        bufp->chgBit(oldp+106,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__sign));
        bufp->chgCData(oldp+107,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__exponent),8);
        bufp->chgIData(oldp+108,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__mantissa),23);
        bufp->chgIData(oldp+109,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__fraction),24);
        bufp->chgCData(oldp+110,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__exponentA),8);
        bufp->chgCData(oldp+111,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__exponentB),8);
        bufp->chgIData(oldp+112,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__fractionA),24);
        bufp->chgIData(oldp+113,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__fractionB),24);
        bufp->chgSData(oldp+114,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+115,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__cout));
        bufp->chgBit(oldp+116,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__eout));
        bufp->chgIData(oldp+117,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__3__KET____DOT__FADD1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+118,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.Y),32);
        bufp->chgIData(oldp+119,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellout__genblk2__BRA__4__KET____DOT__FADD1____pinNumber3),32);
        bufp->chgBit(oldp+120,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__sign));
        bufp->chgCData(oldp+121,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__exponent),8);
        bufp->chgIData(oldp+122,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__mantissa),23);
        bufp->chgIData(oldp+123,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__fraction),24);
        bufp->chgCData(oldp+124,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__exponentA),8);
        bufp->chgCData(oldp+125,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__exponentB),8);
        bufp->chgIData(oldp+126,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__fractionA),24);
        bufp->chgIData(oldp+127,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__fractionB),24);
        bufp->chgSData(oldp+128,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+129,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__cout));
        bufp->chgBit(oldp+130,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__eout));
        bufp->chgIData(oldp+131,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__4__KET____DOT__FADD1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+132,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.Y),32);
        bufp->chgIData(oldp+133,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellout__genblk2__BRA__5__KET____DOT__FADD1____pinNumber3),32);
        bufp->chgBit(oldp+134,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__sign));
        bufp->chgCData(oldp+135,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__exponent),8);
        bufp->chgIData(oldp+136,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__mantissa),23);
        bufp->chgIData(oldp+137,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__fraction),24);
        bufp->chgCData(oldp+138,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__exponentA),8);
        bufp->chgCData(oldp+139,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__exponentB),8);
        bufp->chgIData(oldp+140,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__fractionA),24);
        bufp->chgIData(oldp+141,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__fractionB),24);
        bufp->chgSData(oldp+142,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+143,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__cout));
        bufp->chgBit(oldp+144,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__eout));
        bufp->chgIData(oldp+145,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__5__KET____DOT__FADD1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+146,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.Y),32);
        bufp->chgIData(oldp+147,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellout__genblk2__BRA__6__KET____DOT__FADD1____pinNumber3),32);
        bufp->chgBit(oldp+148,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__sign));
        bufp->chgCData(oldp+149,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__exponent),8);
        bufp->chgIData(oldp+150,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__mantissa),23);
        bufp->chgIData(oldp+151,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__fraction),24);
        bufp->chgCData(oldp+152,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__exponentA),8);
        bufp->chgCData(oldp+153,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__exponentB),8);
        bufp->chgIData(oldp+154,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__fractionA),24);
        bufp->chgIData(oldp+155,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__fractionB),24);
        bufp->chgSData(oldp+156,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+157,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__cout));
        bufp->chgBit(oldp+158,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__eout));
        bufp->chgIData(oldp+159,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__6__KET____DOT__FADD1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+160,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.Y),32);
        bufp->chgIData(oldp+161,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellout__genblk2__BRA__7__KET____DOT__FADD1____pinNumber3),32);
        bufp->chgBit(oldp+162,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__sign));
        bufp->chgCData(oldp+163,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__exponent),8);
        bufp->chgIData(oldp+164,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__mantissa),23);
        bufp->chgIData(oldp+165,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__fraction),24);
        bufp->chgCData(oldp+166,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__exponentA),8);
        bufp->chgCData(oldp+167,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__exponentB),8);
        bufp->chgIData(oldp+168,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__fractionA),24);
        bufp->chgIData(oldp+169,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__fractionB),24);
        bufp->chgSData(oldp+170,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+171,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__cout));
        bufp->chgBit(oldp+172,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__eout));
        bufp->chgIData(oldp+173,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__7__KET____DOT__FADD1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+174,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.Y),32);
        bufp->chgIData(oldp+175,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellout__genblk2__BRA__8__KET____DOT__FADD1____pinNumber3),32);
        bufp->chgBit(oldp+176,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__sign));
        bufp->chgCData(oldp+177,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__exponent),8);
        bufp->chgIData(oldp+178,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__mantissa),23);
        bufp->chgIData(oldp+179,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__fraction),24);
        bufp->chgCData(oldp+180,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__exponentA),8);
        bufp->chgCData(oldp+181,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__exponentB),8);
        bufp->chgIData(oldp+182,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__fractionA),24);
        bufp->chgIData(oldp+183,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__fractionB),24);
        bufp->chgSData(oldp+184,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+185,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__cout));
        bufp->chgBit(oldp+186,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__eout));
        bufp->chgIData(oldp+187,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__8__KET____DOT__FADD1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+188,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.Y),32);
        bufp->chgBit(oldp+189,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__sign));
        bufp->chgCData(oldp+190,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__exponent),8);
        bufp->chgIData(oldp+191,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__mantissa),23);
        bufp->chgIData(oldp+192,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__fraction),24);
        bufp->chgCData(oldp+193,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__exponentA),8);
        bufp->chgCData(oldp+194,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__exponentB),8);
        bufp->chgIData(oldp+195,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__fractionA),24);
        bufp->chgIData(oldp+196,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__fractionB),24);
        bufp->chgSData(oldp+197,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+198,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__cout));
        bufp->chgBit(oldp+199,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__eout));
        bufp->chgIData(oldp+200,(vlSelf->softmaxTB__DOT__soft1__DOT__genblk2__BRA__9__KET____DOT__FADD1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+201,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.ack));
        bufp->chgWData(oldp+202,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__divisors),224);
        bufp->chgIData(oldp+209,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__mulA),32);
        bufp->chgIData(oldp+210,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__oneOrX),32);
        bufp->chgIData(oldp+211,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__outM1),32);
        bufp->chgIData(oldp+212,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__outM2),32);
        bufp->chgIData(oldp+213,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__outA1),32);
        bufp->chgIData(oldp+214,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__outReg),32);
        bufp->chgBit(oldp+215,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__sign));
        bufp->chgCData(oldp+216,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+217,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+218,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+219,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+220,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+221,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+222,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+223,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+224,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__cout));
        bufp->chgBit(oldp+225,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__eout));
        bufp->chgIData(oldp+226,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fAdd1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+227,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul1__DOT__sign));
        bufp->chgCData(oldp+228,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul1__DOT__exponent),8);
        bufp->chgIData(oldp+229,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+230,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul1__DOT__fraction),48);
        bufp->chgIData(oldp+232,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+233,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+234,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul1__DOT__eout));
        bufp->chgIData(oldp+235,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+236,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__divisors[0U]),32);
        bufp->chgBit(oldp+237,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul2__DOT__sign));
        bufp->chgCData(oldp+238,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+239,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+240,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+242,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+243,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+244,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul2__DOT__eout));
        bufp->chgIData(oldp+245,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__0__KET____DOT__exp.__PVT__fMul2__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+246,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.ack));
        bufp->chgWData(oldp+247,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__divisors),224);
        bufp->chgIData(oldp+254,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__mulA),32);
        bufp->chgIData(oldp+255,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__oneOrX),32);
        bufp->chgIData(oldp+256,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__outM1),32);
        bufp->chgIData(oldp+257,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__outM2),32);
        bufp->chgIData(oldp+258,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__outA1),32);
        bufp->chgIData(oldp+259,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__outReg),32);
        bufp->chgBit(oldp+260,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__sign));
        bufp->chgCData(oldp+261,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+262,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+263,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+264,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+265,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+266,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+267,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+268,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+269,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__cout));
        bufp->chgBit(oldp+270,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__eout));
        bufp->chgIData(oldp+271,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fAdd1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+272,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul1__DOT__sign));
        bufp->chgCData(oldp+273,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul1__DOT__exponent),8);
        bufp->chgIData(oldp+274,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+275,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul1__DOT__fraction),48);
        bufp->chgIData(oldp+277,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+278,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+279,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul1__DOT__eout));
        bufp->chgIData(oldp+280,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+281,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__divisors[0U]),32);
        bufp->chgBit(oldp+282,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul2__DOT__sign));
        bufp->chgCData(oldp+283,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+284,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+285,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+287,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+288,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+289,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul2__DOT__eout));
        bufp->chgIData(oldp+290,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__1__KET____DOT__exp.__PVT__fMul2__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+291,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.ack));
        bufp->chgWData(oldp+292,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__divisors),224);
        bufp->chgIData(oldp+299,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__mulA),32);
        bufp->chgIData(oldp+300,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__oneOrX),32);
        bufp->chgIData(oldp+301,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__outM1),32);
        bufp->chgIData(oldp+302,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__outM2),32);
        bufp->chgIData(oldp+303,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__outA1),32);
        bufp->chgIData(oldp+304,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__outReg),32);
        bufp->chgBit(oldp+305,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__sign));
        bufp->chgCData(oldp+306,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+307,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+308,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+309,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+310,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+311,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+312,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+313,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+314,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__cout));
        bufp->chgBit(oldp+315,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__eout));
        bufp->chgIData(oldp+316,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fAdd1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+317,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul1__DOT__sign));
        bufp->chgCData(oldp+318,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul1__DOT__exponent),8);
        bufp->chgIData(oldp+319,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+320,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul1__DOT__fraction),48);
        bufp->chgIData(oldp+322,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+323,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+324,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul1__DOT__eout));
        bufp->chgIData(oldp+325,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+326,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__divisors[0U]),32);
        bufp->chgBit(oldp+327,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul2__DOT__sign));
        bufp->chgCData(oldp+328,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+329,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+330,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+332,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+333,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+334,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul2__DOT__eout));
        bufp->chgIData(oldp+335,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__2__KET____DOT__exp.__PVT__fMul2__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+336,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.ack));
        bufp->chgWData(oldp+337,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__divisors),224);
        bufp->chgIData(oldp+344,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__mulA),32);
        bufp->chgIData(oldp+345,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__oneOrX),32);
        bufp->chgIData(oldp+346,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__outM1),32);
        bufp->chgIData(oldp+347,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__outM2),32);
        bufp->chgIData(oldp+348,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__outA1),32);
        bufp->chgIData(oldp+349,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__outReg),32);
        bufp->chgBit(oldp+350,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__sign));
        bufp->chgCData(oldp+351,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+352,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+353,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+354,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+355,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+356,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+357,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+358,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+359,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__cout));
        bufp->chgBit(oldp+360,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__eout));
        bufp->chgIData(oldp+361,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fAdd1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+362,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul1__DOT__sign));
        bufp->chgCData(oldp+363,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul1__DOT__exponent),8);
        bufp->chgIData(oldp+364,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+365,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul1__DOT__fraction),48);
        bufp->chgIData(oldp+367,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+368,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+369,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul1__DOT__eout));
        bufp->chgIData(oldp+370,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+371,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__divisors[0U]),32);
        bufp->chgBit(oldp+372,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul2__DOT__sign));
        bufp->chgCData(oldp+373,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+374,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+375,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+377,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+378,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+379,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul2__DOT__eout));
        bufp->chgIData(oldp+380,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__3__KET____DOT__exp.__PVT__fMul2__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+381,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.ack));
        bufp->chgWData(oldp+382,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__divisors),224);
        bufp->chgIData(oldp+389,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__mulA),32);
        bufp->chgIData(oldp+390,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__oneOrX),32);
        bufp->chgIData(oldp+391,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__outM1),32);
        bufp->chgIData(oldp+392,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__outM2),32);
        bufp->chgIData(oldp+393,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__outA1),32);
        bufp->chgIData(oldp+394,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__outReg),32);
        bufp->chgBit(oldp+395,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__sign));
        bufp->chgCData(oldp+396,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+397,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+398,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+399,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+400,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+401,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+402,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+403,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+404,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__cout));
        bufp->chgBit(oldp+405,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__eout));
        bufp->chgIData(oldp+406,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fAdd1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+407,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul1__DOT__sign));
        bufp->chgCData(oldp+408,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul1__DOT__exponent),8);
        bufp->chgIData(oldp+409,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+410,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul1__DOT__fraction),48);
        bufp->chgIData(oldp+412,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+413,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+414,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul1__DOT__eout));
        bufp->chgIData(oldp+415,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+416,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__divisors[0U]),32);
        bufp->chgBit(oldp+417,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul2__DOT__sign));
        bufp->chgCData(oldp+418,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+419,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+420,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+422,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+423,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+424,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul2__DOT__eout));
        bufp->chgIData(oldp+425,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__4__KET____DOT__exp.__PVT__fMul2__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+426,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.ack));
        bufp->chgWData(oldp+427,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__divisors),224);
        bufp->chgIData(oldp+434,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__mulA),32);
        bufp->chgIData(oldp+435,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__oneOrX),32);
        bufp->chgIData(oldp+436,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__outM1),32);
        bufp->chgIData(oldp+437,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__outM2),32);
        bufp->chgIData(oldp+438,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__outA1),32);
        bufp->chgIData(oldp+439,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__outReg),32);
        bufp->chgBit(oldp+440,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__sign));
        bufp->chgCData(oldp+441,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+442,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+443,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+444,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+445,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+446,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+447,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+448,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+449,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__cout));
        bufp->chgBit(oldp+450,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__eout));
        bufp->chgIData(oldp+451,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fAdd1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+452,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul1__DOT__sign));
        bufp->chgCData(oldp+453,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul1__DOT__exponent),8);
        bufp->chgIData(oldp+454,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+455,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul1__DOT__fraction),48);
        bufp->chgIData(oldp+457,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+458,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+459,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul1__DOT__eout));
        bufp->chgIData(oldp+460,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+461,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__divisors[0U]),32);
        bufp->chgBit(oldp+462,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul2__DOT__sign));
        bufp->chgCData(oldp+463,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+464,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+465,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+467,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+468,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+469,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul2__DOT__eout));
        bufp->chgIData(oldp+470,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__5__KET____DOT__exp.__PVT__fMul2__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+471,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.ack));
        bufp->chgWData(oldp+472,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__divisors),224);
        bufp->chgIData(oldp+479,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__mulA),32);
        bufp->chgIData(oldp+480,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__oneOrX),32);
        bufp->chgIData(oldp+481,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__outM1),32);
        bufp->chgIData(oldp+482,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__outM2),32);
        bufp->chgIData(oldp+483,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__outA1),32);
        bufp->chgIData(oldp+484,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__outReg),32);
        bufp->chgBit(oldp+485,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__sign));
        bufp->chgCData(oldp+486,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+487,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+488,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+489,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+490,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+491,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+492,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+493,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+494,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__cout));
        bufp->chgBit(oldp+495,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__eout));
        bufp->chgIData(oldp+496,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fAdd1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+497,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul1__DOT__sign));
        bufp->chgCData(oldp+498,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul1__DOT__exponent),8);
        bufp->chgIData(oldp+499,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+500,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul1__DOT__fraction),48);
        bufp->chgIData(oldp+502,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+503,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+504,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul1__DOT__eout));
        bufp->chgIData(oldp+505,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+506,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__divisors[0U]),32);
        bufp->chgBit(oldp+507,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul2__DOT__sign));
        bufp->chgCData(oldp+508,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+509,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+510,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+512,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+513,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+514,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul2__DOT__eout));
        bufp->chgIData(oldp+515,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__6__KET____DOT__exp.__PVT__fMul2__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+516,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.ack));
        bufp->chgWData(oldp+517,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__divisors),224);
        bufp->chgIData(oldp+524,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__mulA),32);
        bufp->chgIData(oldp+525,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__oneOrX),32);
        bufp->chgIData(oldp+526,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__outM1),32);
        bufp->chgIData(oldp+527,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__outM2),32);
        bufp->chgIData(oldp+528,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__outA1),32);
        bufp->chgIData(oldp+529,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__outReg),32);
        bufp->chgBit(oldp+530,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__sign));
        bufp->chgCData(oldp+531,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+532,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+533,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+534,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+535,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+536,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+537,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+538,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+539,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__cout));
        bufp->chgBit(oldp+540,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__eout));
        bufp->chgIData(oldp+541,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fAdd1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+542,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul1__DOT__sign));
        bufp->chgCData(oldp+543,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul1__DOT__exponent),8);
        bufp->chgIData(oldp+544,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+545,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul1__DOT__fraction),48);
        bufp->chgIData(oldp+547,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+548,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+549,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul1__DOT__eout));
        bufp->chgIData(oldp+550,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+551,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__divisors[0U]),32);
        bufp->chgBit(oldp+552,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul2__DOT__sign));
        bufp->chgCData(oldp+553,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+554,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+555,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+557,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+558,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+559,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul2__DOT__eout));
        bufp->chgIData(oldp+560,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__7__KET____DOT__exp.__PVT__fMul2__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+561,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.ack));
        bufp->chgWData(oldp+562,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__divisors),224);
        bufp->chgIData(oldp+569,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__mulA),32);
        bufp->chgIData(oldp+570,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__oneOrX),32);
        bufp->chgIData(oldp+571,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__outM1),32);
        bufp->chgIData(oldp+572,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__outM2),32);
        bufp->chgIData(oldp+573,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__outA1),32);
        bufp->chgIData(oldp+574,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__outReg),32);
        bufp->chgBit(oldp+575,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__sign));
        bufp->chgCData(oldp+576,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+577,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+578,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+579,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+580,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+581,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+582,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+583,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+584,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__cout));
        bufp->chgBit(oldp+585,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__eout));
        bufp->chgIData(oldp+586,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fAdd1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+587,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul1__DOT__sign));
        bufp->chgCData(oldp+588,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul1__DOT__exponent),8);
        bufp->chgIData(oldp+589,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+590,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul1__DOT__fraction),48);
        bufp->chgIData(oldp+592,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+593,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+594,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul1__DOT__eout));
        bufp->chgIData(oldp+595,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+596,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__divisors[0U]),32);
        bufp->chgBit(oldp+597,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul2__DOT__sign));
        bufp->chgCData(oldp+598,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+599,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+600,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+602,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+603,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+604,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul2__DOT__eout));
        bufp->chgIData(oldp+605,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__8__KET____DOT__exp.__PVT__fMul2__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+606,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.ack));
        bufp->chgWData(oldp+607,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__divisors),224);
        bufp->chgIData(oldp+614,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__mulA),32);
        bufp->chgIData(oldp+615,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__oneOrX),32);
        bufp->chgIData(oldp+616,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__outM1),32);
        bufp->chgIData(oldp+617,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__outM2),32);
        bufp->chgIData(oldp+618,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__outA1),32);
        bufp->chgIData(oldp+619,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__outReg),32);
        bufp->chgBit(oldp+620,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__sign));
        bufp->chgCData(oldp+621,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+622,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+623,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+624,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+625,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+626,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+627,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+628,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+629,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__cout));
        bufp->chgBit(oldp+630,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__eout));
        bufp->chgIData(oldp+631,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fAdd1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+632,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul1__DOT__sign));
        bufp->chgCData(oldp+633,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul1__DOT__exponent),8);
        bufp->chgIData(oldp+634,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul1__DOT__mantissa),23);
        bufp->chgQData(oldp+635,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul1__DOT__fraction),48);
        bufp->chgIData(oldp+637,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul1__DOT__fractionA),24);
        bufp->chgIData(oldp+638,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul1__DOT__fractionB),24);
        bufp->chgBit(oldp+639,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul1__DOT__eout));
        bufp->chgIData(oldp+640,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul1__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+641,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__divisors[0U]),32);
        bufp->chgBit(oldp+642,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul2__DOT__sign));
        bufp->chgCData(oldp+643,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+644,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+645,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+647,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+648,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+649,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul2__DOT__eout));
        bufp->chgIData(oldp+650,(vlSymsp->TOP__softmaxTB__DOT__soft1__DOT__genblk1__BRA__9__KET____DOT__exp.__PVT__fMul2__DOT__unnamedblk1__DOT__i),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[5U])) {
        bufp->chgIData(oldp+651,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__x1),32);
        bufp->chgIData(oldp+652,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y1Out),32);
        bufp->chgIData(oldp+653,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__x2),32);
        bufp->chgIData(oldp+654,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__x3),32);
        bufp->chgIData(oldp+655,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__x4),32);
        bufp->chgBit(oldp+656,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__sign));
        bufp->chgCData(oldp+657,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__exponent),8);
        bufp->chgIData(oldp+658,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__mantissa),23);
        bufp->chgIData(oldp+659,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__fraction),24);
        bufp->chgCData(oldp+660,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__exponentA),8);
        bufp->chgCData(oldp+661,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__exponentB),8);
        bufp->chgIData(oldp+662,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__fractionA),24);
        bufp->chgIData(oldp+663,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__fractionB),24);
        bufp->chgSData(oldp+664,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__shiftAmount),9);
        bufp->chgBit(oldp+665,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__cout));
        bufp->chgBit(oldp+666,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__eout));
        bufp->chgIData(oldp+667,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yAdd1__DOT__unnamedblk1__DOT__i),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[6U])) {
        bufp->chgIData(oldp+668,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y2D),32);
        bufp->chgIData(oldp+669,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y2S),32);
        bufp->chgIData(oldp+670,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y3Out),32);
        bufp->chgBit(oldp+671,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul3__DOT__sign));
        bufp->chgCData(oldp+672,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul3__DOT__exponent),8);
        bufp->chgIData(oldp+673,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul3__DOT__mantissa),23);
        bufp->chgQData(oldp+674,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul3__DOT__fraction),48);
        bufp->chgIData(oldp+676,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul3__DOT__fractionA),24);
        bufp->chgIData(oldp+677,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul3__DOT__fractionB),24);
        bufp->chgBit(oldp+678,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul3__DOT__eout));
        bufp->chgIData(oldp+679,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul3__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+680,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul4__DOT__sign));
        bufp->chgCData(oldp+681,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul4__DOT__exponent),8);
        bufp->chgIData(oldp+682,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul4__DOT__mantissa),23);
        bufp->chgQData(oldp+683,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul4__DOT__fraction),48);
        bufp->chgIData(oldp+685,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul4__DOT__fractionA),24);
        bufp->chgIData(oldp+686,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul4__DOT__fractionB),24);
        bufp->chgBit(oldp+687,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul4__DOT__eout));
        bufp->chgIData(oldp+688,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul4__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+689,((0x80000000U | (0x7fffffffU 
                                                 & vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y2D))),32);
        bufp->chgBit(oldp+690,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__sign));
        bufp->chgCData(oldp+691,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__exponent),8);
        bufp->chgIData(oldp+692,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__mantissa),23);
        bufp->chgIData(oldp+693,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__fraction),24);
        bufp->chgCData(oldp+694,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__exponentA),8);
        bufp->chgCData(oldp+695,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__exponentB),8);
        bufp->chgIData(oldp+696,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__fractionA),24);
        bufp->chgIData(oldp+697,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__fractionB),24);
        bufp->chgSData(oldp+698,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__shiftAmount),9);
        bufp->chgBit(oldp+699,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__cout));
        bufp->chgBit(oldp+700,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__eout));
        bufp->chgIData(oldp+701,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub3__DOT__unnamedblk1__DOT__i),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[7U])) {
        bufp->chgIData(oldp+702,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y3D),32);
        bufp->chgIData(oldp+703,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y3S),32);
        bufp->chgIData(oldp+704,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y4Out),32);
        bufp->chgBit(oldp+705,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul4__DOT__sign));
        bufp->chgCData(oldp+706,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul4__DOT__exponent),8);
        bufp->chgIData(oldp+707,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul4__DOT__mantissa),23);
        bufp->chgQData(oldp+708,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul4__DOT__fraction),48);
        bufp->chgIData(oldp+710,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul4__DOT__fractionA),24);
        bufp->chgIData(oldp+711,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul4__DOT__fractionB),24);
        bufp->chgBit(oldp+712,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul4__DOT__eout));
        bufp->chgIData(oldp+713,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul4__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+714,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul5__DOT__sign));
        bufp->chgCData(oldp+715,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul5__DOT__exponent),8);
        bufp->chgIData(oldp+716,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul5__DOT__mantissa),23);
        bufp->chgQData(oldp+717,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul5__DOT__fraction),48);
        bufp->chgIData(oldp+719,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul5__DOT__fractionA),24);
        bufp->chgIData(oldp+720,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul5__DOT__fractionB),24);
        bufp->chgBit(oldp+721,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul5__DOT__eout));
        bufp->chgIData(oldp+722,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul5__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+723,((0x80000000U | (0x7fffffffU 
                                                 & vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y3D))),32);
        bufp->chgBit(oldp+724,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__sign));
        bufp->chgCData(oldp+725,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__exponent),8);
        bufp->chgIData(oldp+726,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__mantissa),23);
        bufp->chgIData(oldp+727,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__fraction),24);
        bufp->chgCData(oldp+728,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__exponentA),8);
        bufp->chgCData(oldp+729,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__exponentB),8);
        bufp->chgIData(oldp+730,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__fractionA),24);
        bufp->chgIData(oldp+731,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__fractionB),24);
        bufp->chgSData(oldp+732,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__shiftAmount),9);
        bufp->chgBit(oldp+733,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__cout));
        bufp->chgBit(oldp+734,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__eout));
        bufp->chgIData(oldp+735,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub4__DOT__unnamedblk1__DOT__i),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[8U])) {
        bufp->chgIData(oldp+736,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y1D),32);
        bufp->chgIData(oldp+737,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y1S),32);
        bufp->chgIData(oldp+738,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y2Out),32);
        bufp->chgBit(oldp+739,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul2__DOT__sign));
        bufp->chgCData(oldp+740,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul2__DOT__exponent),8);
        bufp->chgIData(oldp+741,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul2__DOT__mantissa),23);
        bufp->chgQData(oldp+742,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul2__DOT__fraction),48);
        bufp->chgIData(oldp+744,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul2__DOT__fractionA),24);
        bufp->chgIData(oldp+745,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul2__DOT__fractionB),24);
        bufp->chgBit(oldp+746,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul2__DOT__eout));
        bufp->chgIData(oldp+747,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__fMul2__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+748,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul3__DOT__sign));
        bufp->chgCData(oldp+749,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul3__DOT__exponent),8);
        bufp->chgIData(oldp+750,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul3__DOT__mantissa),23);
        bufp->chgQData(oldp+751,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul3__DOT__fraction),48);
        bufp->chgIData(oldp+753,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul3__DOT__fractionA),24);
        bufp->chgIData(oldp+754,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul3__DOT__fractionB),24);
        bufp->chgBit(oldp+755,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul3__DOT__eout));
        bufp->chgIData(oldp+756,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__yMul3__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+757,((0x80000000U | (0x7fffffffU 
                                                 & vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y1D))),32);
        bufp->chgBit(oldp+758,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__sign));
        bufp->chgCData(oldp+759,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__exponent),8);
        bufp->chgIData(oldp+760,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__mantissa),23);
        bufp->chgIData(oldp+761,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__fraction),24);
        bufp->chgCData(oldp+762,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__exponentA),8);
        bufp->chgCData(oldp+763,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__exponentB),8);
        bufp->chgIData(oldp+764,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__fractionA),24);
        bufp->chgIData(oldp+765,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__fractionB),24);
        bufp->chgSData(oldp+766,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__shiftAmount),9);
        bufp->chgBit(oldp+767,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__cout));
        bufp->chgBit(oldp+768,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__eout));
        bufp->chgIData(oldp+769,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__ySub2__DOT__unnamedblk1__DOT__i),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[9U])) {
        bufp->chgIData(oldp+770,(vlSelf->softmaxTB__DOT__soft1__DOT__outMul),32);
        bufp->chgBit(oldp+771,(vlSelf->softmaxTB__DOT__soft1__DOT__FM1__DOT__sign));
        bufp->chgCData(oldp+772,(vlSelf->softmaxTB__DOT__soft1__DOT__FM1__DOT__exponent),8);
        bufp->chgIData(oldp+773,(vlSelf->softmaxTB__DOT__soft1__DOT__FM1__DOT__mantissa),23);
        bufp->chgQData(oldp+774,(vlSelf->softmaxTB__DOT__soft1__DOT__FM1__DOT__fraction),48);
        bufp->chgIData(oldp+776,(vlSelf->softmaxTB__DOT__soft1__DOT__FM1__DOT__fractionA),24);
        bufp->chgIData(oldp+777,(vlSelf->softmaxTB__DOT__soft1__DOT__FM1__DOT__fractionB),24);
        bufp->chgBit(oldp+778,(vlSelf->softmaxTB__DOT__soft1__DOT__FM1__DOT__eout));
        bufp->chgIData(oldp+779,(vlSelf->softmaxTB__DOT__soft1__DOT__FM1__DOT__unnamedblk1__DOT__i),32);
    }
    bufp->chgBit(oldp+780,(vlSelf->softmaxTB__DOT__clk));
    bufp->chgIData(oldp+781,(vlSelf->softmaxTB__DOT__soft1__DOT__expRec),32);
    bufp->chgIData(oldp+782,(vlSelf->softmaxTB__DOT__soft1__DOT____Vcellinp__FM1____pinNumber1),32);
    bufp->chgIData(oldp+783,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y1),32);
    bufp->chgIData(oldp+784,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y2),32);
    bufp->chgIData(oldp+785,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y3),32);
    bufp->chgIData(oldp+786,(vlSelf->softmaxTB__DOT__soft1__DOT__FR__DOT__y4),32);
}

void VsoftmaxTB___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    VsoftmaxTB___024root__trace_cleanup\n"); );
    // Init
    VsoftmaxTB___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<VsoftmaxTB___024root*>(voidSelf);
    VsoftmaxTB__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[3U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[4U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[5U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[6U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[7U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[8U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[9U] = 0U;
}
